FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y build-essential libpq-dev

COPY workers/paper_scraper/requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY workers ./workers
COPY shared ./shared

CMD ["celery", "-A", "shared.celery.app:celery_app", "worker", "--loglevel=info", "-Q", "scraper"]
