"""
initial
Revision ID: 8c29b1fcc46b
Revises: 
Create Date: 2026-03-17 17:13:38.599483
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8c29b1fcc46b'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('authors', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('keywords', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('original_pdf_path', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.Column('simplified_text_beginner', sa.Text(), nullable=True),
    sa.Column('simplified_text_intermediate', sa.Text(), nullable=True),
    sa.Column('simplified_text_advanced', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_processing_status'), ['processing_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_publication_date'), ['publication_date'], unique=False)

    op.create_table('topics',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('slug'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('profile_type', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='profiletype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('likes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'article_id', name='unique_user_article_like')
    )
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_likes_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_likes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_likes_user_id'), ['user_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic_slug', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_slug'], ['topics.slug'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_topic_slug'), ['topic_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)

    # Trigger para atualizar updated_at na tabela users (implementação correta em PL/pgSQL)
    op.execute(
        """
        CREATE OR REPLACE FUNCTION update_users_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = NOW();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER update_users_updated_at
        BEFORE UPDATE ON users 
        FOR EACH ROW EXECUTE FUNCTION update_users_updated_at();
        """
    )

    # Inserts padrão de topics (mantendo todo o conjunto do SQL original)
    op.execute(
        """
        INSERT INTO topics (name, slug, description) VALUES
            ('Inteligência Artificial', 'inteligencia-artificial', 'IA, sistemas inteligentes, raciocínio automático e aplicações'),
            ('Arquitetura de Hardware', 'arquitetura-de-hardware', 'Arquitetura de processadores, microarquitetura e sistemas embarcados'),
            ('Complexidade Computacional', 'complexidade-computacional', 'Teoria da complexidade, classes de complexidade e problemas intratáveis'),
            ('Engenharia Computacional, Financeira e Científica', 'engenharia-computacional-financeira-e-cientifica', 'Modelagem numérica, simulação e aplicações em finanças e ciências'),
            ('Geometria Computacional', 'geometria-computacional', 'Algoritmos para problemas geométricos, estruturas e aplicações'),
            ('Computação e Linguagem', 'computacao-e-linguagem', 'Processamento de linguagem natural, semântica e linguística computacional'),
            ('Criptografia e Segurança', 'criptografia-e-seguranca', 'Criptografia, segurança de redes, privacidade e proteção de dados'),
            ('Visão Computacional e Reconhecimento de Padrões', 'visao-computacional-e-reconhecimento-de-padroes', 'Detecção, reconhecimento e análise de imagens e vídeo'),
            ('Computadores e Sociedade', 'computadores-e-sociedade', 'Impacto social, ética, políticas públicas e implicações sociais da computação'),
            ('Bancos de Dados', 'bancos-de-dados', 'Modelagem, armazenamento, consultas e otimização em bancos de dados'),
            ('Computação Distribuída, Paralela e em Cluster', 'computacao-distribuida-paralela-e-em-cluster', 'Sistemas distribuídos, paralelismo, escalabilidade e computação em cluster'),
            ('Bibliotecas Digitais', 'bibliotecas-digitais', 'Catalogação, preservação e acesso a coleções digitais'),
            ('Matemática Discreta', 'matematica-discreta', 'Combinatória, teoria dos grafos e estruturas discretas'),
            ('Estruturas de Dados e Algoritmos', 'estruturas-de-dados-e-algoritmos', 'Projetos de algoritmos, análise e estruturas de dados'),
            ('Tecnologias Emergentes', 'tecnologias-emergentes', 'Computação quântica, blockchain e novas tecnologias em P&D'),
            ('Linguagens Formais e Teoria dos Autômatos', 'linguagens-formais-e-teoria-dos-automatos', 'Autômatos, gramáticas e teoria formal de linguagens'),
            ('Literatura Geral', 'literatura-geral', 'Artigos de revisão, ensaios e visão geral sobre temas em computação'),
            ('Gráfica Computacional', 'grafica-computacional', 'Renderização, modelagem 3D, visualização e gráficos por computador'),
            ('Ciência da Computação e Teoria dos Jogos', 'ciencia-da-computacao-e-teoria-dos-jogos', 'Aplicações da teoria dos jogos, algoritmos econômicos e teoria dos mecanismos'),
            ('Interação Humano-Computador', 'interacao-humano-computador', 'UX, design de interfaces, usabilidade e estudo de interação'),
            ('Recuperação de Informação', 'recuperacao-de-informacao', 'Sistemas de busca, indexação, recuperação e ranking de documentos'),
            ('Teoria da Informação', 'teoria-da-informacao', 'Codificação, compressão, entropia e comunicação de informação'),
            ('Aprendizado de Máquina', 'aprendizado-de-maquina', 'Modelos de aprendizado supervisionado, não supervisionado e deep learning'),
            ('Lógica na Ciência da Computação', 'logica-na-ciencia-da-computacao', 'Verificação formal, lógica matemática e especificação de sistemas'),
            ('Sistemas Multiagente', 'sistemas-multiagente', 'Agentes autônomos, coordenação e sistemas distribuídos multiagente'),
            ('Multimídia', 'multimidia', 'Processamento de áudio, vídeo, imagens e aplicações multimídia'),
            ('Software Matemático', 'software-matematico', 'Ferramentas, bibliotecas e algoritmos para matemática computacional'),
            ('Análise Numérica', 'analise-numerica', 'Métodos numéricos, aproximação e solução de problemas contínuos por métodos computacionais'),
            ('Computação Neural e Evolutiva', 'computacao-neural-e-evolutiva', 'Redes neurais, algoritmos evolutivos e otimização baseada em evolução'),
            ('Redes e Arquitetura da Internet', 'redes-e-arquitetura-da-internet', 'Protocolos de rede, roteamento, infraestrutura e arquiteturas de internet'),
            ('Outras Áreas de Ciência da Computação', 'outras-ciencias-da-computacao', 'Tópicos diversos e interdisciplinares em computação'),
            ('Sistemas Operacionais', 'sistemas-operacionais', 'Kernel, gerenciamento de processos, memória e abstrações de sistema'),
            ('Desempenho', 'desempenho', 'Medição, otimização e análise de desempenho de software e hardware'),
            ('Linguagens de Programação', 'linguagens-de-programacao', 'Design de linguagens, compiladores, interpretadores e semântica'),
            ('Robótica', 'robotica', 'Percepção, controle, planejamento e sistemas robóticos'),
            ('Computação Simbólica', 'computacao-simbolica', 'Manipulação simbólica, álgebra computacional e sistemas simbólicos'),
            ('Som', 'som', 'Processamento de áudio, síntese, análise e reconhecimento de som'),
            ('Engenharia de Software', 'engenharia-de-software', 'Processos, metodologias, testes e arquitetura de software'),
            ('Redes Sociais e de Informação', 'redes-sociais-e-de-informacao', 'Análise de grafos, difusão de informação e comportamento em redes sociais'),
            ('Sistemas e Controle', 'sistemas-e-controle', 'Teoria de controle, sistemas dinâmicos e automação')
        ON CONFLICT (slug) DO NOTHING;
        """
    )

    # ### end Alembic commands ###

def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_topic_slug'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_likes_user_id'))
        batch_op.drop_index(batch_op.f('ix_likes_created_at'))
        batch_op.drop_index(batch_op.f('ix_likes_article_id'))

    op.drop_table('likes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_slug'))

    op.drop_table('topics')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_publication_date'))
        batch_op.drop_index(batch_op.f('ix_articles_processing_status'))

    op.drop_table('articles')


    # Reverter inserts e objetos criados explicitamente
    op.execute('DROP TRIGGER IF EXISTS update_users_updated_at ON users;')
    op.execute('DROP FUNCTION IF EXISTS update_users_updated_at();')

    # Remove the profiletype enum type
    op.execute("DROP TYPE IF EXISTS profiletype;")
    # ### end Alembic commands ###